-- 코드를 입력하세요
SELECT A.AUTHOR_ID AS AUTHOR_ID,
    B.AUTHOR_NAME AS AUTHOR_NAME,
    A.CATEGORY AS CATEGORY,
    SUM(A.PRICE * C.SALES) AS TOTAL_SALES
FROM (BOOK AS A JOIN AUTHOR AS B
     ON A.AUTHOR_ID = B.AUTHOR_ID) JOIN BOOK_SALES AS C
     ON A.BOOK_ID = C.BOOK_ID
WHERE YEAR(C.SALES_DATE) = 2022
    AND
    MONTH(C.SALES_DATE) = 1
GROUP BY 1, 3
ORDER BY 1, 3 DESC