-- 코드를 작성해주세요

SELECT
    A.ITEM_ID AS ITEM_ID,
    A.ITEM_NAME AS ITEM_NAME,
    A.RARITY AS RARITY
FROM ITEM_INFO AS A INNER JOIN ITEM_TREE AS B
    ON A.ITEM_ID = B.ITEM_ID
WHERE 1=1
    AND B.ITEM_ID NOT IN (SELECT PARENT_ITEM_ID
                          FROM ITEM_TREE
                          WHERE PARENT_ITEM_ID IS NOT NULL
                          GROUP BY PARENT_ITEM_ID)
ORDER BY A.ITEM_ID DESC