-- 코드를 입력하세요
SELECT B.ANIMAL_ID AS ANIMAL_ID, B.NAME AS NAME 
FROM ANIMAL_INS AS A RIGHT JOIN ANIMAL_OUTS AS B
ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.DATETIME IS NOT NULL
    AND 
    A.DATETIME IS NULL
ORDER BY ANIMAL_ID