-- 코드를 입력하세요
SELECT B.HISTORY_ID AS HISTORY_ID,
    ROUND((DATEDIFF(B.END_DATE, B.START_DATE) + 1)
         * CASE
                WHEN(DATEDIFF(B.END_DATE, B.START_DATE) + 1 < 7) THEN A.DAILY_FEE
                WHEN(DATEDIFF(B.END_DATE, B.START_DATE) + 1 < 30) THEN (A.DAILY_FEE * 0.95)
                WHEN(DATEDIFF(B.END_DATE, B.START_DATE) + 1 < 90) THEN (A.DAILY_FEE * 0.92)
                ELSE (A.DAILY_FEE * 0.85)
          END) AS FEE  
FROM (CAR_RENTAL_COMPANY_CAR AS A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
    ON A.CAR_ID = B.CAR_ID) JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
    ON A.CAR_TYPE = C.CAR_TYPE
WHERE A.CAR_TYPE = '트럭'
GROUP BY 1
ORDER BY 2 DESC, 1 DESC
