-- 코드를 입력하세요
SELECT C.APNT_NO AS APNT_NO, A.PT_NAME AS PT_NAME, C.PT_NO AS PT_NO, B.MCDP_CD AS MCDP_CD, B.DR_NAME AS DR_NAME, C.APNT_YMD AS APNT_YMD
FROM (PATIENT AS A JOIN APPOINTMENT AS C
     ON A.PT_NO = C.PT_NO) JOIN DOCTOR AS B
     ON C.MDDR_ID = B.DR_ID
WHERE B.MCDP_CD = 'CS'
     AND C.APNT_CNCL_YN = 'N'
     AND DATE_FORMAT(C.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
 ORDER BY APNT_YMD