-- 코드를 작성해주세요
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS AS A
WHERE EXISTS (SELECT NAME
             FROM SKILLCODES AS B
             WHERE CATEGORY = 'Front End'
                AND B.CODE = A.SKILL_CODE & B.CODE)
ORDER BY ID