-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE CAR_ID IN (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE 8 <= MONTH(START_DATE) AND MONTH(START_DATE) <= 10
                GROUP BY CAR_ID
                HAVING COUNT(*) >= 5)
        AND 8 <= MONTH(START_DATE) AND MONTH(START_DATE) <= 10
GROUP BY MONTH(START_DATE), CAR_ID
HAVING COUNT(*) >= 1
ORDER BY MONTH, CAR_ID DESC

