SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS AS B
WHERE EXISTS (SELECT 1
             FROM SKILLCODES AS A 
             WHERE A.NAME IN ('Python', 'C#') AND
             B.SKILL_CODE & A.CODE = A.CODE )
ORDER BY ID