-- 코드를 작성해주세요

SELECT SUM(C.SCORE) AS SCORE,
    B.EMP_NO AS EMP_NO,
    B.EMP_NAME AS EMP_NAME,
    B.POSITION AS POSITION,
    B.EMAIL AS EMAIL
FROM HR_EMPLOYEES AS B INNER JOIN HR_GRADE AS C
    ON B.EMP_NO = C.EMP_NO
WHERE C.YEAR = 2022
GROUP BY C.YEAR, C.EMP_NO
ORDER BY SCORE DESC
LIMIT 1